### PR TITLE
Add installation instructions

### LINKED ISSUE #1: Create installation instructions
Start.

### PR DESCRIPTION
**Pull request by JohnGiorgi**
Adds installation instructions (for `conda` and `jupyter`) to the web page.

**TODO**

- [x] ~~How are we expecting students to access the jupyter notebooks? By cloning or downloading this whole repository? (cloning requires them to have `git` installed)~~ Via website, OK.
- [ ] I have no way of verifying the windows instructions, but I got them right from Anacondas docs. Can someone test them in the next 2 weeks?

Closes #1.

### CODE REVIEW

**Comment by daniyall** [comment]
The notebooks will be downloadable from the website. Right now it only has the html files, but I'm working on linking the notebook files.
I also don't have a way of verifying windows instructions.

**Comment by JohnGiorgi** [comment]
Okay, this should be good. Installation instructions are really verbose, but I think they have to be for people who have never touched the command line before. 

The only thing I am unable to do is test this on windows. @mghassem are you able to do this? If not, we should be fine, instructions came straight from Anaconda docs.

**Comment by mghassem** [comment]
Sorry John, I accepted Daniyal's merge before and destroyed your PR in the process. :/

Can you rebase and send me the patches?

**Comment by JohnGiorgi** [comment]
I really hope I did that right!

**Pull request merged**
